# Generated by Django 5.2.17 on 2026-10-09 09:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0127_infinity_steering_referential"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueSteering",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_start", "À démarrer"),
                            ("in_progress", "En cours"),
                            ("in_validation", "En validation"),
                            ("waiting", "En attente"),
                            ("done", "Terminé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="to_start",
                        max_length=20,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                (
                    "waiting_for",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("internal", "Interne"),
                            ("client_partner", "Client / partenaire"),
                            ("regulatory", "Réglementaire"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("waiting_since", models.DateTimeField(blank=True, null=True)),
                (
                    "risk_nature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("financial", "Financier"),
                            ("regulatory", "Réglementaire"),
                            ("legal", "Juridique"),
                            ("schedule", "Calendrier"),
                            ("reputation", "Réputation"),
                            ("governance", "Gouvernance"),
                            ("hr", "RH"),
                            ("operational", "Opérationnel"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("risk_effective_date", models.DateField(blank=True, null=True)),
                ("risk_description", models.TextField(blank=True, default="")),
                ("closure_date", models.DateField(blank=True, null=True)),
                ("closure_comment", models.TextField(blank=True, default="")),
                ("situation", models.TextField(blank=True, default="")),
                ("situation_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_steerings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="db.steeringcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issues",
                        to="db.entity",
                    ),
                ),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="steering", to="db.issue"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="issue_steerings", to="db.project"
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_steerings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="issue_steerings", to="db.workspace"
                    ),
                ),
            ],
            options={
                "db_table": "issue_steerings",
            },
        ),
    ]
